project:
  type: website
  post-render: _post-render.py
  preview:
    port: 4200


profile:
  default: english
  group: 
    - [english, french]
    
format:
  pdf: 
    fontsize: 16pt
  html:
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"

execute: 
  freeze: true

#metadata-files: 
  #- _quarto-french.yml
  #- _quarto-english.yml

editor: visual

