project:
  type: website
  post-render: _post-render.py
  preview:
    port: 4200


profile:
  default: english
  group: 
    - [english, french]
    
format:
  pdf: 
    documentclass: scrreprt

execute: 
  freeze: true

#metadata-files: 
  #- _quarto-french.yml
  #- _quarto-english.yml

editor: visual

