lang: fr

project: 
  title: "Français avec Kunal"
  type: website
  output-dir: docs/fr

website:
  favicon: images\logo.png
  page-navigation: true
  title: "Français avec Kunal"
 
  page-footer:
    left: 
      - text: Éthique
        href: ethics.qmd
      - text: Politique de confidentialité
        href: policy.qmd
      - text: Conditions de service
        href: terms.qmd   

    right:
      - text: Se connecter
        href: login.qmd
      - text: English
        href: https://frenchwithkunal.ca/index.html
      - text: Français
        href: https://frenchwithkunal.ca/fr/index.html
      - icon: envelope
        href: mailto:info@frenchwithkunal.ca       
      - icon: youtube
        href: https://www.youtube.com/@frenchwithkunal
    
    center: |
      @2025 Français avec Kunal <br>
       Tous droits reservés. <br>
       
  navbar:
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Nous Contacter"
        href: contact.qmd
      - text: Abonnement
        href: payment.qmd
      - text: "Accès"
        menu:
          - text: "Se connecter"
            href: login.qmd
          - text: "Se déconnecter"
            href: profile.qmd
    right:
      - text: "Facturation"
        href: https://billing.stripe.com/p/login/14k8xo9FteB0dr26oo
      - text: "FAQ's"
        href: faq.qmd
      - text: Langue
        menu:
          - text: Anglais
            href: https://frenchwithkunal.ca/index.html
          - text: Français
            href: https://frenchwithkunal.ca/fr/index.html        
      - icon: youtube
        href: https://www.youtube.com/@frenchwithkunal

format:
  html:
    theme: 
      light: cerulean
      dark: cyborg
    #fontsize: 1.1em
    #linestretch: 1.7
    css: styles.css
    toc: true

execute:
  freeze: true
  increment: true
  cache: true
