lang: fr

project: 
  title: "Français avec Kunal"
  type: website
  output-dir: docs/fr

website:
  favicon: images\logo.png
  page-navigation: true
  title: "Français avec Kunal"
  page-footer:
    left: 
      - text: Éthique
        href: ethics.qmd
      - text: Politique de confidentialité
        href: policy.qmd
      - text: Conditions de service
        href: terms.qmd

    right:
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Français
            href: posts/fr.qmd         
      - icon: youtube
        href: https://www.youtube.com/@kunalkhurana7822
    
    center: |
      @2025 Français avec Kunal <br>
       Tous droits reservés. <br>
       
  navbar:
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Nous Contacter"
        href: contact.qmd
    right:
      - href: https://frenchwithkunal.ca/
        text: English
      - href: docs\fr\index.html
        text: Français 
format:
  html:
    theme: 
      light: cerulean
      dark: cyborg
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true