lang: fr

project: 
  title: "Français avec Kunal"
  type: website
  output-dir: docs/fr

website:
  favicon: images\banner_kk.png
  page-navigation: true
  title: "Français avec Kunal"
  site-url: "https://frenchwithkunal.ca"
  open-graph: true
  twitter-card: true

  announcement: 
    icon: info-circle
    dismissable: true
    content: >
      **🎉 Bonne nouvelle !**  
      Rejoignez notre *Communauté d'apprentissage du français* et profitez d'une **classe d'essai GRATUITE** !  
       📘 Découvrez des **ressources exclusives** [comme celle-ci](https://frenchwithkunal.ca/fr/posts/28042025/conver2.html) pour accélérer votre apprentissage :  
        - **Conseils de grammaire** pour maîtriser les bases et les subtilités.  
        - **Exercices d'écoute** pour améliorer votre compréhension orale.  
        - **Activités interactives** pour rendre l'apprentissage amusant et efficace !  
      👉 Rendez-vous sur la page [Abonnement](https://frenchwithkunal.ca/fr/payment.html) pour en savoir plus.
    type: success
    position: below-navbar
  
  search:
    location: navbar
    type: overlay
    show-item-context: true
  
  page-footer:
    left:
      - text: Éthique
        href: ethics.qmd
      - text: Politique de confidentialité
        href: policy.qmd
      - text: Conditions d'utilisation
        href: terms.qmd

    right:
      - text: Connexion
        href: login.qmd
      - text: Anglais
        href: https://frenchwithkunal.ca/index.html
      - text: Français
        href: https://frenchwithkunal.ca/fr/index.html
      - icon: envelope
        href: mailto:frenchwithkunal@gmail.com
      - icon: youtube
        href: https://www.youtube.com/@frenchwithkunal 
      
    center: |
      @2025 Français avec Kunal <br>
      Tous droits réservés. <br>
  
  navbar:
    background: primary
    logo: images\banner_kk.png
    logo-alt: "Français avec Kunal"
    collapse-below: lg
    
    left:
      - text: "Ressources"
        menu: 
          - text: "Articles de Blog"
            href: posts.qmd
            icon: file
          - text: "Exercices"
            href: exercises.qmd
            icon: clipboard-check
      - text: "À Propos"
        href: about.qmd      
      - text: "Contactez-nous"
        href: contact.qmd
      - text: Abonnement
        href: payment.qmd
      - text: "Accès"
        menu:
          - text: "Connexion"
            href: login.qmd
            icon: box-arrow-in-right
          - text: "Déconnexion"
            href: profile.qmd
            icon: box-arrow-right
          - text: "Portail de Facturation"
            href: https://billing.stripe.com/p/login/9AQcPg2i52jtaSk4gg
            icon: credit-card
        
    right:
      - text: "FAQ"
        href: faq.qmd
        icon: question-circle
      - text: Langue
        menu:
          - text: Anglais
            href: https://frenchwithkunal.ca/index.html
            icon: globe
          - text: Français
            href: https://frenchwithkunal.ca/fr/index.html
            icon: globe
      - icon: youtube
        href: https://www.youtube.com/@frenchwithkunal
        text: "Chaîne YouTube"

  sidebar:
    - id: navigation
      title: "Liens Rapides"
      style: floating
      align: left
      contents:
        - text: "Articles de Blog"
          href: posts.qmd
          icon: file-lines
        - text: "À Propos"
          href: about.qmd
          icon: info-circle
        - text: "Contact"
          href: contact.qmd
          icon: envelope
        - text: "FAQ"
          href: faq.qmd
          icon: question-circle
        - text: "Abonnement"
          href: payment.qmd
          icon: credit-card

format:
  html:
    theme: 
      light: cerulean
      dark: cyborg
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 900px
    code-copy: true
    code-overflow: wrap

editor: visual

execute:
  freeze: auto
  echo: false
  warning: false
  cache: true
  fig-align: center
